name: Deploy React App to Azure Blob Storage

on:
  push:
    branches:
      - main  # Or change to the branch you want to trigger deployment from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az login --service-principal \
              --username ${{ secrets.AZURE_CLIENT_ID }} \
              --password ${{ secrets.AZURE_CLIENT_SECRET }} \
              --tenant ${{ secrets.AZURE_TENANT_ID }}

            az storage blob upload-batch \
              --account-name akmalcloudnative \
              --destination \$web \
              --source ./build \
              --overwrite
